[package]
name = "interpreter"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
parser = { path = "../parser" }

[target.wasm32-unknown-unknown.dependencies]
wasm-bindgen = "0.2.87"
js-sys = "0.3.64"
