[package]
name = "repl"
version = "0.1.0"
edition = "2021"

[dependencies]
console = { version = "0.15.7" }
parser = { path = "../parser" }
scanner = { path = "../scanner" }
interpreter = { path = "../interpreter" }
